package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/CheckUser.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\"\"http://www.w3.org/TR/REC-html40/loose.dtd\">\r\n");
      out.write('\r');
      out.write('\n');

	if (session.getAttribute("userName") == null || session.getAttribute("repositorySession") == null) {
    String forwardTo = "LoginForm.jsp";
	if (request.getQueryString() != null ) {
        //forwardTo +="?" + URLEncoder.encode(request.getRequestURI() + "?" + request.getQueryString());
    }
     forwardTo = "Reload.html";

      out.write('\r');
      out.write('\n');
      out.write('	');
      if (true) {
        _jspx_page_context.forward( forwardTo );
        return;
      }
      out.write('\r');
      out.write('\n');

	}
	else {
		//System.out.println("User = " + session.getAttribute("userName"));
	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<!-- Generated by Volante Repository -->\r\n");
      out.write("<TITLE>Volante Repository</TITLE>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<FRAMESET rows=\"52,*\" frameborder=no border=0>\r\n");
      out.write("\t<FRAME src=\"banner.html\" name=\"bannerFrame\" frameborder=\"no\" border=\"0\" scrolling=\"no\" noresize marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("\t<FRAMESET cols=\"20%,80%\" border=3 scrolling=auto frameborder=yes >\r\n");
      out.write("\t\t<FRAME src=\"explorer.jsp\" name=\"explorerFrame\"  scrolling=auto>\r\n");
      out.write("\t\t<FRAME src=\"UnpublishedIndex.jsp\" name=\"detailFrame\"  scrolling='yes'>\r\n");
      out.write("\t</FRAMESET> \r\n");
      out.write("</FRAMESET>\r\n");
      out.write("<NOFRAMES>\r\n");
      out.write("<H2>\r\n");
      out.write("Frame Alert</H2>\r\n");
      out.write("<P>\r\n");
      out.write("This document is designed to be viewed using the frames feature. If you see this message, you are using a non-frame-capable web client.\r\n");
      out.write("<BR>\r\n");
      out.write("Link to <A HREF=\"\">Non-frame version.</A></P>\r\n");
      out.write("\r\n");
      out.write("</NOFRAMES>\r\n");
      out.write("</HTML>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
